services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.3
    container_name: es
    environment:
      - node.name=es-node
      - discovery.type=single-node
      - cluster.name=weather-cluster
      - "ES_JAVA_OPTS=-Xms3g -Xmx6g"
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - "ES_JAVA_HOME=/usr/share/elasticsearch/jdk"

    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep green"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy

  indexer:
    build: ./indexer
    container_name: indexer
    volumes:
      - ./parquet:/data/parquet
    environment:
      - ES_HOST=http://elasticsearch:9200
      - ES_INDEX=weather_statuses
    depends_on:
      - elasticsearch
    restart: unless-stopped

volumes:
  esdata:
